<!DOCTYPE html>
<html><head>
<meta charset="utf-8">
<meta http-equiv="refresh" content="0; url=https://docs.carbon-transparency.org/tr/data-exchange-protocol/latest/openapi.yaml">
</head>
<body></body></html>
