sequenceDiagram
    participant D as Data Recipient
    participant H as Data Owner

    Note over D, H: Data Recipient requests one <br/> or more PCFs from data owner
    D->>H: POST [data-owner]/3/events <br/>RequestCreated Event
    Activate H
    break Does not accept event
        H->>D: Returns with HTTP Code 400
    end

    H->>D: Returns with HTTP Code 200
    Deactivate H

    Note over D, H: Data owner now processes<br/> the request.
    H->>H: Data owner decides on processing<br/>potentially involving skilled personnel

    Note over D, H: Data owner sends an event back <br/>to the recipient
    alt PCFs have been created or found
        H->>D: POST [data-recipient]/3/events <br/>RequestFulfilledEvent
    else No PCFs could be found or created
        H->>D: POST [data-recipient]/3/events <br/>RequestRejectedEvent
    end
