#!/usr/bin/env python3
import sys
import re

# This script is used to patch the output html file generated by Bikeshed and
# add the status and version to the title of the html file.
#
# It takes 2 parameters: 
#  - the path to a bikeshed source file
#  - the (already generated) output html file 
#
# The script parses the header of the bikeshed file to determine STATUS, DATE and VERSION.
# These are included in the bikeshed source file as follows:
#
#   Text Macro: DATE 20241021
#   Text Macro: VERSION 2.3.0
#   Text Macro: STATUS Release|Consultation|Draft
#

# Parse the bikeshed file to extract the title, date, version and status.
def parse_bikeshed_file(bikeshed_file):
    with open(bikeshed_file, 'r') as file:
        content = file.read()
    match = re.search(r'Title:\s+(.*)\n', content)
    title = match.group(1) if match else None

    match = re.search(r'Text Macro: DATE\s+(\d+)', content)
    date = match.group(1) if match else None
    
    match = re.search(r'Text Macro: VERSION\s+([\d.]+)', content)
    version = match.group(1) if match else None
    
    match = re.search(r'Text Macro: STATUS\s+(\w+)', content)
    status = match.group(1) if match else None
    
    return title, date, version, status

CUSTOM_CSS = """
<style>
pre, code, samp {
  font-style: normal;
}
dfn > code {
  font-weight: normal;
}
[data-link-type=element]::before,
[data-link-type=element]::after
{
  content: initial;
}
.json-schema-type {
  font-family: monospace;
  font-size: 0.9em;
}
.json-schema-enum code {
  background-color: rgba(100,100,100,0.03);
  color: #666;
  font-size: 0.8em;
  border: 1px solid rgba(100,100,100,0.9);
  border-radius: 2px;
  padding: 2px;
  margin-top: 6px;
  margin-left: 0px;
  margin-right: 0px;
  display: inline-block;
}
.json-schema-required {
/*  background-color: rgba(0,0,160,0.05);
  background-color: rgba(0,0,160,0.9);
  border-color: rgba(0,0,160,0.9);
  font-size: 0.8em;
  border-style: solid;
  border-width: 1px;
  border-radius: 2px;
  padding: 2px;
  margin: 1px;
  display: inline-block;*/
  color: rgba(160,0,0,0.9);
}
</style>
"""

# Patch the already generated html file with adapted title and status.
def update_html_file(html_file, title, status):
    with open(html_file, 'r') as file:
        content = file.read()  
    content = re.sub(r'(<title>).*(</title>)', r'\1' + title + r'\2', content, count=1)
    content = re.sub(r'(<h1 .*>).*(</h1>)', r'\1' + title + r'\2', content, count=1)
    content = re.sub(r'(<h2 .* id="profile-and-date">).*(</h2>)', r'\1' + status + r'\2', content, count=1)
    # Patch some CSS as well. 
    content = re.sub(r'^\s*<body', CUSTOM_CSS + '<body', content, count=1, flags=re.MULTILINE)
    with open(html_file, 'w') as file:
        file.write(content)

# Pacth the spec
def patchup(input, output):
    title, date, version, status = parse_bikeshed_file(input)
    if title is None:
        raise "Title not found"
    
    if status == "Release":
        title += f" (Version {version})"
    elif status in ["Draft", "Consultation"]:
        title += f" (Version {version}-{date})"
    else:
        print("Unknown status")
        return
    
    update_html_file(output, title, status)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: patch-up-spec.py <bikeshed_file> <html_file>")
        sys.exit(1)
    
    patchup(sys.argv[1], sys.argv[2])
