name: CI
on:
  # pull_request: {}
  push
jobs:
  main:
    name: Build and Validate
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          SOURCE: spec/index.bs
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          SOURCE: spec/v2/index.bs
