name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create release
        run: sh ./spec/release.sh
      - name: Get date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY_MM_DD HH_mm_ss_SSS"
      - name: Push release to tr/${{steps.date.outputs.year}}
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: "spec/release"
          destination-github-username: "wbcsd"
          destination-repository-name: "tr"
          user-email:
          target-directory: ./${{steps.date.outputs.year}}/data-exchange-protocol-${{steps.date.outputs.year}}${{steps.date.outputs.month}}${{steps.date.outputs.day}}
          target-branch: release-v${{inputs.version}}-${{steps.date.outputs.year}}${{steps.date.outputs.month}}${{steps.date.outputs.day}}
          create-target-branch-if-needed: true
          commit-message: "Release v${{inputs.version}}"
      - name: Push release to tr/data-exchange-protocol
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: "spec/release"
          destination-github-username: "wbcsd"
          destination-repository-name: "tr"
          user-email:
          target-directory: ./data-exchange-protocol
          target-branch: release-v${{inputs.version}}-${{steps.date.outputs.year}}${{steps.date.outputs.month}}${{steps.date.outputs.day}}
          create-target-branch-if-needed: true
          commit-message: "Release v${{inputs.version}}"
